Traceback (most recent call last):
  File "d:\Documentos\GitHub\Python\Automate the Boring Stuff with Python\Chapter-11\11-1.py", line 28, in <module>
    raise Exception("Error 2")
Exception: Error 2
